### PR TITLE
Changes teg sprites

### PR DESCRIPTION
**Pull request by alexkar598**
:cl: alexkar598
tweak: Ported TEG sprites from vgstation
/:cl:

tegcapture

dont ask me to see either the old sprite or it working because im too lazy

### CODE REVIEW

**Comment by niceping** [comment]
What about overlays? Like teg_middle for TEG and cold/hot overlays for circulators?

**Comment by alexkar598** [comment]
overlays should be working?

**Comment by ghost** [comment]
thought so

**Comment by miniusAreas** [comment]
@alexkar598 reeee build error

**Comment by alexkar598** [comment]
Il do a more complete port of the PR later

**Pull request closed without merging**
