### PR TITLE
restores the plasmacutter to its former glory

### PR DESCRIPTION
**Pull request by ghost**
i can't code

:cl: adam
balance: Plasma cutters do full damage and can dismember again, rather than being tickle guns that do less than a punch on average.
/:cl:

### CODE REVIEW

**Review by alexkar598 — DISMISSED** [review]
LGTM

**Comment by alexkar598** [comment]
Dismemberment -1

**Review by ghost — CHANGES_REQUESTED** [review]
Not modular. Did you even look at it, alex?

**Comment by miniusAreas** [comment]
@AdamElTablawy fix this shit, but also at the same time THANK YOU YOU MADMAN.

**Comment by alexkar598** [comment]
Wrong tab,wrong review whoops

**Comment by Quantum-M** [comment]
Strongly disagree, the weapon was fairly strong and any creep that gets to the protolathe computer doesn't have to worry about materials or research levels can easily get it. Mining also has a other set of stuff to use besides the cutter.

**Comment by ghost** [comment]
i can't really be arsed to pick apart why that's a stupid statement and people are more likely to listen to you than me, so

**Comment by niceping** [comment]
rip

**Pull request closed without merging**
