### PR TITLE
resprites for rnd and some servers

### PR DESCRIPTION
**Pull request by Crysoskis**
[Changelogs]: # 
:cl: ooo look purdies

imageadd: Added new sprites for the Autolathe and variants
imageadd: Added new sprites for the Circuit Imprinter and variants
imageadd: Added new sprites for the Destructive Analyser
imageadd: Added new sprites for servers

/:cl:

### CODE REVIEW

**Review by ghost — DISMISSED** [review]
LGTM

**Comment by Wilchenx** [comment]
whats lgtm

also pics please

**Comment by azzzertyy** [comment]
looks good to me

**Comment by alexkar598** [comment]
@Wilchenx LGTM = looks good to me and for sprites you can go in the checks tab under icondiffbot

**Review by ghost — DISMISSED** [review]

**Review by ghost — APPROVED** [review]

**Pull request merged**
