### PR TITLE
[Ready For Review] Medbay Remap + Side edits + Sprite additions

### PR DESCRIPTION
**Pull request by Quantum-M**
**NOTE:** This is technically ready for testing, although one thing I wish to do is to quickly change the medibots to be similar to the new medkit sprites I made.

:cl: 
add: Several different colored office chairs.
del: Removed chaplain's soul shard.
tweak: Remapped medbay and added new rooms to it.
tweak: Cremator room was switched with the garden/coffin room in chapel, chapel lounge now requires chaplain access.
tweak: Gave all the security offices and posts their own red chairs.
fix: Minor map edits, like adding missed lights or decals to the floors, along with giving security a secway.
tweak: Genetics are now solely medbay department, no science staff has access to it anymore, and genetics has no science access.
tweak: Moved the security and medbay security boards from tech storage to their own departments.
/:cl:

Huge work that touches medbay and other parts. See map difference.

**Medbay** 

Massive remap, bigger with less of a cluttered look. Chemistry was given no grenade supplies, as that is the sort of thing we do not want to encourage with our intent of midRP. Medbay in overall has less medkits, along with cloning having no mannitol and mutadone pill bottles, forcing the chemists to actually _try and do work_ instead of making some random death/meme chem the whole shift.

Genetics has been given to medbay, any ties it had with science has been cut off. The RD, scientist, and roboticist do not have access to genetics in any way or form. The geneticist, likewise, has no access to any science parts. At that, the geneticist solely has genetics access, barring the CMO and the Captain, as genetic powers, which is usually why are there, are not essential to medbay and genetics defects can be countered with mutadone.

Medbay was given a secondary storage, only accessible to the CMO. It has spare supplies to medbay and the CMO's space suit. It also has medbay's protolathe and tech storage's medbay boards.

Medbay has been given two surgery rooms, a patient ward, and a exam room, along with a bigger front desk.

In general, medbay is now more anti-assistant, hopefully deterring the sort of "self-serve" players.

**Chapel**

The chapel had it's cremator and coffin/flower area switched. Reasoning to this is that the cremator is located in a extremely isolated area, along with the fact that it can be easily broken into. The cremator can now only be access via breaking some walls down, directly through the chapel or chaplain's office, or through space, this gives any victims of antags that are overzealous on permakilling some chance, along with making it harder for changelings to go and cheese by destroying the cremator.

Soul shard was removed from the Chaplain's validhunting arsenal. Reasons are this: Instant body destroying item that needs the victim to be at least unconscious or death to work, along with making the victim a crappy, simple mob. Think on whether or not a **_NON-ANTAG_** chaplain should even have this to begin with.

**Other**

Some minor map fixes done, mainly to the security areas, where they were given some missing lights, and the secway.

Tech storage boards that had the security and medbay boards were moved to their own relevant departments, considering that tech storage is largely there to be broken into and have the items stolen.

**Medibots**
medibotgroup

### CODE REVIEW

**Comment by Quantum-M** [comment]
Ready for review.

**Comment by ghost** [comment]
```sunset/code/game/area/Space_Station_13_areas.dm:48:error: music: undefined var```

Needs fixing

**Comment by Quantum-M** [comment]
Fixed

**Comment by Ziiro** [comment]
The reason tech storage has those boards is replacing machinery that gets destroyed in case medbay gets cratered. Putting it in the same department runs the risk of losing the backups in the same event that destroys the primaries.

Then again this is already true with the departmental lathe boards, so who knows

**Review by ghost — APPROVED** [review]
Noice

**Pull request merged**
