### PR TITLE
New airlocks

### PR DESCRIPTION
**Pull request by Crysoskis**
[Changelogs]: #

:cl: dor-a-thon
add: Added new appearances for station airlocks
soundadd: Added new sounds for airlocks
/:cl:

newdoordemo

more coming soonish

### CODE REVIEW

**Comment by scrubmcnoob** [comment]
Very nice.

**Review by alexkar598 — DISMISSED** [review]

**Comment by miniusAreas** [comment]
LGTM AAAAAAAA HOLY SHIT THIS IS NICE AS FUCK.

**Comment by alexkar598** [comment]
Ce office sprite not present,external airlock sprite not there

**Comment by Quantum-M** [comment]
I rather like the small bleeping noise it makes when you open it, although here are some suggestions:

When the airlock opens, I recommend you lower the intensity/loudness of the hiss, it feels a bit too loud.
The frame of the airlock should probably be lighter, it stands out a lot when the airlock opens.

**Comment by ghost** [comment]
Airlocks that still need to be done:
Normal
External
Secure

Whatever this is

**Comment by ShattForte** [comment]
Very nice, would also like to see you do an isometric version.

**Comment by miniusAreas** [comment]
I almost mistook these for goondoors my god.

**Pull request merged**
