### PR TITLE
Antag OOC

### PR DESCRIPTION
**Pull request by Autodidactic-Intelligence**
Adds antag ooc.

### CODE REVIEW

**Comment by ghost** [comment]
is this tested?

**Comment by ghost** [comment]
Won't merge until this is tested

**Comment by scrubmcnoob** [comment]
@steamp0rt It's working.

**Comment by SmokingKilz** [comment]
@MemeProof @Crysoskis If this is all good, lets please have this merged.

**Comment by SunsetStationuser** [comment]
@SmokingKilz  has this been tested?

**Pull request merged**
