### PR TITLE
new sm reactions

### PR DESCRIPTION
**Pull request by Crysoskis**
[Changelogs]: # 
:cl: 
add: Added more gas interactions for the supermatter
/:cl:

Tritium is a very bad, being the gas with the highest heat penalty, twice as plasma
Pluoxium is oxygen+ as usual, now the engine reacts accordingly
Hyper Noblium is essentially a supermatter extinguisher being able to cool the engine quick at the cost of severely retarding the reaction and making it generate little energy if any
Nitryl does n2o's job in adding heat resistance to the core, but its nearly twice as effective

### CODE REVIEW

**Comment by Crysoskis** [comment]
@kingoftheautism 
boneman10

**Review by alexkar598 — CHANGES_REQUESTED** [review]
removed_gas will always be null

**Comment by Crysoskis** [comment]
> can you add WHAT the gas reactions are

done and done @steamp0rt

**Comment by ghost** [comment]
Tritium is sometimes generated as a byproduct of the SM. This won't make it go boom boom due to that, will it?

**Comment by Crysoskis** [comment]
In certian situations with a specific gas mixture yes, but usually at that point its really, really far gone

**Pull request merged**
