### PR TITLE
Test branch

### PR DESCRIPTION
**Pull request by Shock223**
Went ahead and fixed up Virology's healing effect to resemble Oracles while keeping the good parts.  Also added Viral metabolism back in. 

I left out hunger effecting ones such as Weight Gain and Weight Even. I plan on buffing Spaceacillin on a later date to help give counter play to the more obnoxious effects. If that doesn't help, I plan revisiting Viro to increase the hunger rate for it's usage. 

Let me know if there are any issues that you see with this.

### CODE REVIEW

**Comment by Wilchenx** [comment]
this + nanites would basically make people outheal any damage

this is absolutely awfull for balance

**Comment by FlattestGuitar** [comment]
\>massive amount of changes
\>seemingly arbitrary, no explanation for any one adjustment other than "it's from Oracle"
\>PR heavily affects game balance, even though there have only been like five shifts total, which means balance will be rather hard to adjust for at this stage

🤔

**Comment by Shock223** [comment]
Thanks you for the feedback. It is appreciated. 

The reason why I made the PR is, at base, TG station virology is very ineffective if you are wishing to assist the station as a non antagonist. 

It uses the following symptoms: 

Starlight Condensation: only useful if outside the station. Replaced Toxin Filter 

Tissue Hydration: Only useful if you are drinking water. Replaced Tissue Regrowth

Nocturnal Regeneration: Only really useful in maint and even that is dubious. Replaced Regeneration  

Radioactive Resonance: Only useful when there is a radiation storm or standing next to the SM. Replaced Deoxyribonucleic Acid Restoration.

The higher level ones are only slightly "better". 

Plasma Fixation: only useful when you are breathing plasma (Great for the plasmamen miners out there I guess): Replaced Temperature Adaptation.

Regenerative Coma is really the only worthwhile addition and even that is dubious because the last thing you want getting close to death is to lose access to your character when you need access the most. 

With the examples listed, the stars quite literally have to align to actually make a virus useful to the station. 

With that being said, the ability of Oracle's virology was fairly strong and in addition to this, Sunset already has Nanites in the department of Science. Having both creates the issue of how do the two work together. TG already seen this issue and included the Nanites.dm in it's files for it to do so. 

From a design point of view I see the following pathways developing: 

Virus vs Nanites: Have them be mutually exclusive going forward. By taking one, you lose the ability to deal with the other. This will require a bit of working in terms developing the pros and cons of each. I personally dislike this method as it limits the extradepartment interaction between Science and Medbay. 

Virus with Nanites: This path allows for more interesting developments (not to mention allow for the Virologist to get out of the lab). Possible ideas is to get rid of the level 8 symptom for active effects in favor of boosting Nanite effects and vice versa. I much prefer this path as it aids interdepartmental gameplay and coordination as well. Something that is sorely needed. 

For virology without Nanites, I see the following changes. 

Change Spaceacillin so that the virus stage drops to 1 and remains at one while the character still has it in their system while keeping the rest of Spaceacillin's effect active. In effect, suppressing the symptoms of the viral agent. This will make the drug more valuable when there is an antag virologist on the station as well as limited the more extreme effects of say a very powerful healing virus. 

Second thing is add additional ingredients to the gels that are required for the stable and unstable gels. To get them currently, you simply need to run to the ORM, have access to a blender, and the chem machines to do so. Given the Virologist has chem access, there needs to be something more to prevent their apex healing virus from being pilled up and good to go at the 15 minute mark. I am pondering having them go to hydro to request a certain plant for the gels but I am open for other ideas as well. 

I know this PR most likely won't go through but I figured Sunset is still in development and it would be a good exercise with github. That and as well putting down my thoughts to pen on some issues that I have seen and currently see. 

Thank you for your time,

**Comment by Shock223** [comment]
As discussed, I will close this PR and come with a new one once ways to balance it have been hammered out before hand. 

Thank you.

**Pull request closed without merging**
