### PR TITLE
Changes the engine floor sprites

### PR DESCRIPTION
**Pull request by alexkar598**
:cl: alexkar598
tweak: tweaked the reinforced floor sprite
/:cl:
now is:
imperial colony nine 2018-09-23 110100

compared to:
ss13 ru yellow circus rogue roost papa 2018-05-20 190351

### CODE REVIEW

**Review by ghost — DISMISSED** [review]
LGTM

**Comment by alexkar598** [comment]
travis borked

**Comment by niceping** [comment]
first, that "compared to" is old /tg/ reinforced floor sprite
second, oof
oof

I will throw actual vg screenshots later

**Comment by alexkar598** [comment]
@SunsetStation/commit-access please get it merged/closed but do something

**Pull request merged**
