### PR TITLE
Changes the floor tiles

### PR DESCRIPTION
**Pull request by Quantum-M**
Changes the regular floor tiles to be their own style, also changes the carpet tiles to be more red than that ugly faded, brown orange color. Also updates the red, blue and green circuit floors to be their own style.

:cl: 
tweak: Updates the regular floor tiles.
tweak: Updates the red carpet to be more red.
tweak: Updates the red, blue, green circuit floors.
/:cl:

floorfour

floorthree

floortwo

carpettwo

### CODE REVIEW

**Comment by Quantum-M** [comment]
Edits needed, please hold

**Comment by alexkar598** [comment]
Carpet and wood is amazing!other floor tiles are nice but circuit floors are terrible IMO,doesn't look futury enough

**Review by miniusAreas — DISMISSED** [review]
LGTM. Quite nice work quantum, floors are great.

**Review by ghost — CHANGES_REQUESTED** [review]
Don't edit the /tg/ DMIs

Instead, make new DMIs in the `sunset/icons` folder, and override them

For example,
```
/turf/open/floor
 icon = 'icons/turf/floors.dmi'
```

**Comment by SmokingKilz** [comment]
> 
> 
> I don't like warden's office or circuit floors.

I think that's the point in relation to circuit floors. I believe it's meant to be a glass panel with wiring and the sorts under it.

Personally my only concern is how will the tiles look when they're wet.

**Review by ghost — DISMISSED** [review]
Ok, I modularized this for you. LGTM, but some people are complaining about how shiny everything is.

**Comment by Wilchenx** [comment]
generally when changing sprites you should improve the sprites, your floor sprites clash with every other object in the game, they're definitely way too shiny.

**Comment by Wilchenx** [comment]
image

**Comment by Keluandrie** [comment]
@Wilchenx
Circlejerk IRC comments from nobody relevant to the project aren't exactly productive, homie. they're being actively worked on by someone producing content for us, and criticism is and has been accepted, but autistic screeching has never really counted as such.

**Comment by ghost** [comment]
@Wilchenx While feedback and criticism is appreciated, blatant insults and toxicity isn't. Although I do have a heavy dislike for the shiny floors, it's best to simply just say what and why.

**Comment by ghost** [comment]
circuit floor tiles look bad
A) they look like glass over 
B) vaguely defined lines that no longer have that circuity look

**Comment by ghost** [comment]
I like the idea, but the community hates it.

**Pull request closed without merging**
