### PR TITLE
Replaces bigtext loud mode on headsets with bold text

### PR DESCRIPTION
**Pull request by alexkar598**
:cl: alexkar598
tweak: Replaced the big text loud mode on headsets with bold text.
/:cl:

bigtext loud boi is gone

### CODE REVIEW

**Comment by alexkar598** [comment]
DNM until i figure out tgui

**Comment by alexkar598** [comment]
Figured it out

**Comment by ghost** [comment]
May I suggest leaving it in, but instead of making messages big, it just makes them bold?

**Comment by alexkar598** [comment]
Done @steamp0rt

**Review by ghost — COMMENTED** [review]
LGTM

**Review by ghost — APPROVED** [review]
LGTM

**Pull request merged**
