### PR TITLE
Brig Overhaul [DNM] [DNTM]

### PR DESCRIPTION
**Pull request by miniusAreas**
[Changelogs]: #119 but under my name (hopefuly i did this fucking right)
:cl: miniusAreas added
edit: Makes brig more simplistic, while also adding some color-refs.
/:cl:

[why]: # To make us diffrent than metastation, because it can get boring.

### CODE REVIEW

**Comment by miniusAreas** [comment]
@steamp0rt Did i do it right?

**Comment by ghost** [comment]
You didn't add the map

**Comment by ghost** [comment]
And to reset to YOUR latest github branch (you WILL lose un-pushed changes!)
```
git fetch origin
git reset --hard origin/master
git checkout HEAD .
```

**Comment by ghost** [comment]
You're going to need to do the reset, since I just overrided your branch and updated it to master, while removing the merge commits and adding the map and stuff

**Comment by miniusAreas** [comment]
blarg

**Comment by ghost** [comment]
Wtf? I fixed everything for you

**Comment by miniusAreas** [comment]
@SunsetStationuser Reminder that this is not to be testmerged until i fix the critically broken disposals and several atmos pipes, undocumented changes, etc.

**Comment by miniusAreas** [comment]
With the creation of #362, This PR has been abandoned and left for anyone to finish. Until #362 is resolved, there will be no updates unless a miracle happens. Godspeed, whoever commandeers this.

**Comment by Quantum-M** [comment]
I started a brig remap my self.

**Comment by alexkar598** [comment]
Since this is abandoned I'm going to have to close this if anyone wants to take over feel free to make a new pull request.

**Comment by alexkar598** [comment]
Author requested reopen,it will have to be approved by staff because at this point we dont need yet another brig remap IMO

**Comment by alexkar598** [comment]
Please make another PR for it as you changed your concept quite drasticly

**Pull request closed without merging**
