### PR TITLE
GPS cords as a target in Teleporter Consoles

### PR DESCRIPTION
**Pull request by FluffySensation**
Lets you put a GPS into the Teleporter Console to use saved cords as a target like how you could in Oracle.

### CODE REVIEW

**Comment by Quantum-M** [comment]
This was a functionality in Oracle?

**Comment by FluffySensation** [comment]
Yeah Im the one who fixed it on oracle

**Review by alexkar598 — DISMISSED** [review]
LGTM

**Comment by FluffySensation** [comment]
well I didn't mean to add this to this pr but its related so I guess it doesn't matter

**Pull request closed without merging**
