### PR TITLE
Puts real timers

### PR DESCRIPTION
**Pull request by alexkar598**
Puts the 5,10,15 timer scheme 
:cl: alexkar598
fix: Brig Timers now follow the 5,10,15 presets
/:cl:

[why]: Following the real thing

### CODE REVIEW

**Review by ghost — DISMISSED** [review]
Looks fine, just add sunset start/end

**Comment by miniusAreas** [comment]
@alexkar598 Why are we adding brig timers to be longer? The idea of genpop was to replace cells, and having both seems redundant and unfair for those who get shoved into a cell.

**Comment by Quantum-M** [comment]
@miniusAreas The current brig has no time cells at all, this is most likely if we ever go back to the old cell system or we add one or two cells back.

**Comment by miniusAreas** [comment]
Ah, makes more sense

**Comment by alexkar598** [comment]
@steamp0rt done

**Review by ghost — APPROVED** [review]
I still think we should just move to genpop entirely

**Pull request merged**
