### PR TITLE
Adds Blueshield Office

### PR DESCRIPTION
**Pull request by Quantum-M**
:cl: 
add: Blueshield Office and spawn point.
add: Blueshield pet, Stanley, added to the office.
del: Removed the whole gateway room.
tweak: Adds some missed lights to the lawyer office.
/:cl:

Gives the Blueshield a office, along with the spawn point and locker. It is located in the Gateway atrium. The gateway also has been ripped out, made into a maintanance, and the shutters were changed to construction access, in case someone wants to build something there. Also, the Blueshield gets a pet named Stanley.

Minor fix to the lawyer office as light switches were accidentally left out

blueshield

### CODE REVIEW

**Review by ghost — APPROVED** [review]
Looks good to me. Gateway is never used anyways

**Review by alexkar598 — CHANGES_REQUESTED** [review]
Gateway is used as swarmer spawn point

**Comment by niceping** [comment]
And why we always need to remove gateways? I know it's was not used in ages, but duh

**Comment by alexkar598** [comment]
will this make diffbutt run?

**Comment by alexkar598** [comment]
Il close this pull request in favour of another pull request(to run mapdiffbot)

**Pull request closed without merging**
