### PR TITLE
Scooter & Scooter Bounty Removal

### PR DESCRIPTION
**Pull request by FluffySensation**
crafting scooters via rods, crafting menu and by adding rods to a skateboard removed.

### CODE REVIEW

**Comment by alexkar598** [comment]
@stre

**Comment by alexkar598** [comment]
Urg ,didn't mean to make a comment,sorry stre

**Comment by miniusAreas** [comment]
@FluffySensation Make ATVs purchaseable from cargo without hacking if your doing this for real, else miners will hate you.

**Comment by FluffySensation** [comment]
Hi @miniusAreas
This decision was not made in a vacuum and was part of a list that I took up. If you are worried about movement speed there are plenty ways to increase it. There will also at some point be a re-balancing of lava land mobs to compensate for our slower walk speed.

**Comment by Quantum-M** [comment]
Scooters moving in a rocky, treacherous terrain is a very dumb concept.

**Comment by niceping** [comment]
ah shit another mining lifeboat is getting removed, and we also have speed slower than it was on oracle, gonna rush those biker crates

**Comment by FluffySensation** [comment]
Hi @kingoftheautism 
I think your being a little melodramatic. Just like I said to minius and seems to be one of your main concerns in your comment, lava land mobs will get a re-balance to deal with the change in speed. For the concern over getting your speed boosts you will now have to rely on chem and botany just like how most station have to rely on you.

**Comment by niceping** [comment]
or, you know, just get nuka cola lmao

**Comment by FluffySensation** [comment]
So what are you complaining about?

**Comment by MoXuT0** [comment]
I agree that this is just fun removal PR. What's the point in removing scooters? Miners abusing it? Why not just rebalance lavaland mobs speed (The sooner the better)?

**Comment by FluffySensation** [comment]
Okay, thanks for the feedback. Since there seems to be some contention over this I'll go though why the staff came to the conclusion that scooters don't add as much as they take away.

First let's establish what scooters do. Scooters for almost no effort, make you permanently faster and unslippable. This from a gameplay point of view is questionable in itself but its not like it couldn't be made more reasonable but I suspect you would still be on here saying it was a joy killing pr if some sort of nerf was introduced.

So now lets go over what they allow you to do. They are a straight buff to your combat potential this gets exaggerated slightly by Sunsets slower movement speed.

This is where in my opinion all the fun comes from with scooters. Its a low effort way that increases the amount you can do without interacting positively with the rest of the crew. Being able to clear lava land solo so you can show off how good a miner you are, laughing at sec as you kite all their shots with your extra movement speed. This is where what you, if you could call them positives ends because now we get into RP.

You can say what you want about Sunset RP or lack of it at the moment but it doesn't change the fact that Sunsets goal is to be MRP and that the staff are working for free to try to accomplish this.

So there is not much to say about the RP value of scooters, An adult to be riding around on a corporate station is ludicrous and scooters working on Lavaland even more so.

So to conclude scooters have questionable balance, encourage less cooperation between the divisions and have no RP value. To me it seems you are complaining because you don't get to have an advantage over players who care in the slightest about RP and how you will have to try a little harder to be able to clear Lavaland.

Thanks for reading

**Comment by ghost** [comment]
> An adult to be riding around on a corporate station is ludicrous and scooters working on Lavaland even more so.

Yeah, but isn't NT all about efficiency?

**Comment by miniusAreas** [comment]
@FluffySensation @kingoftheautism @steamp0rt 
Ive come with a solution for this, and by god it just might work.
Is it possible to make scooters ***slower*** on ash and non-man materials and faster on man materials, and ATVs faster on ash and slower on plating?
It seems like a good compromise for a controversial issue, possibly making ATVs something purchasable from the point machine.

**Comment by miniusAreas** [comment]
Scooters dont work in space, so im pretty sure theres a var or some shit to prevent them from working in a certain tile_open if not to slow them.

**Pull request closed without merging**
