### PR TITLE
Originally by FlattestGuitar - Medical Rework

### PR DESCRIPTION
**Pull request by Alex-Selvey**
Originally by FlattestGuitar - adds breaking bones and body scanner
PR's from FlattestGuitar Ported:
https://github.com/OracleStation/OracleStation/pull/5
https://github.com/OracleStation/OracleStation/pull/12
https://github.com/OracleStation/OracleStation/pull/296
https://github.com/OracleStation/OracleStation/pull/551
https://github.com/OracleStation/OracleStation/pull/716

## About The Pull Request

This addition adds both the ability to break bones and a body scanner. Broken bones cause pain and can hinder the player in various ways (ex. broken legs slow the player down). Splints have been added to partially fix broken bones while waiting for surgery. A body scanner has also been added. Body scanner shows several medical points of a patient and better assists medbay. Brain damage has also been slightly tweaked.

Body scanner is working
Bones are breaking
organ damage working

## Changelog
:cl:Originally by FlattestGuitar - Ported By MemeProof
add: Breaking Bones
add: Splints to fix bones
add: Body Scanner
tweak: tweaked brain damage overall
balance: balances how much damage is dealt to the brain
iconadd: Splints

/:cl:

EDIT:
added a little bit of missed code
fixed bones
also fixes a small issue with sec turnstiles in perma

### CODE REVIEW

**Comment by SunsetStationuser** [comment]
@MemeProof  has this been tested?

**Comment by Alex-Selvey** [comment]
Everything works except for bones aren't breaking. I need help figuring out what isn't working with bones.

**Comment by SunsetStationuser** [comment]
@MemeProof has the broken bones been fixed?

**Comment by Alex-Selvey** [comment]
Not yet. I have not been able to identify what the problem is.

**Pull request merged**
