### PR TITLE
Sanity Rework

### PR DESCRIPTION
**Pull request by ghost**
:cl: Floyd / Qustinnus
add: Big sanity rework
/:cl:

ill type this out later or let the designers do it

### CODE REVIEW

**Comment by SunsetStationuser** [comment]
@Qustinnus update to fix travis

**Comment by ghost** [comment]
the github owners can just restart the build

**Comment by SunsetStationuser** [comment]
actually it will continue to fail, if you aren't up to date with the most recent version of the master branch. I just restarted the build, and it continues to fail.

**Comment by ghost** [comment]
smh it was up to date u chumbis

**Comment by ghost** [comment]
or rather, not conflicting with master.

**Comment by SunsetStationuser** [comment]
im running the build to see why it keeps failing

**Comment by ghost** [comment]
its your t r a v i s

**Comment by SunsetStationuser** [comment]
[21:10:47] Runtime in code/controllers/subsystem.dm,66: Subsystem fire coderbus(/datum/controller/subsystem/mood) does not fire() but did not set the SS_NO_FIRE flag. Please add the SS_NO_FIRE flag to any subsystem that doesn't fire so it doesn't get added to the processing list and waste cpu.

**Comment by ghost** [comment]
thats a bug with TG code, there's no way to fix this here. I am using fire() just not in the regular way.

**Comment by SunsetStationuser** [comment]
https://pastebin.com/MyWMYFBm

**Comment by SunsetStationuser** [comment]
can't see any reason other than that error for the build to return fail?

**Pull request merged**
